[package]
name = "marketplace-engine"
version = "0.1.0"
description = "TicketToken Secondary Marketplace Engine"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "marketplace_engine"

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
spl-token = "4.0.0"
